[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rag_milvus"
version = "0.1.1"
dependencies = [
  "pymilvus"
]

[tool.setuptools.packages.find]
where = ["src"]
